gns3-gui: unpin python3Packages
revert d203ca98569fca1f9a0641a30cd9841b3b646c0a
from https://github.com/NixOS/nixpkgs/pull/326646
which created derivations with 2 python versions (3.11 + 3.12)
which breaks the import of rpds:
ModuleNotFoundError: No module named 'rpds.rpds'
https://github.com/python-jsonschema/jsonschema/issues/1175